#! /bin/bash

# Install Docker on the machine and also add the "workshop" user to the
# "docker" group, in order to let them use Docker without sudo.

set -e

# Install Docker
apt-get update
apt-get -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
apt-get update
apt-get install -y docker-ce

# Setup workshop user
useradd -m workshop -s /bin/bash
addgroup workshop sudo
addgroup workshop docker
echo "workshop:${vm_password}" | chpasswd

# Install kubelet, kubectl and kubeadm
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -y kubelet kubeadm kubectl
apt-mark hold kubelet kubeadm kubectl

# Get the machine ready
kubeadm config images pull
sysctl net.bridge.bridge-nf-call-iptables=1
echo "source <(kubectl completion bash)" >> /home/workshop/.bashrc
systemctl daemon-reload
systemctl restart kubelet
