#! /bin/bash

# Install Docker on the machine and also add the "workshop" user to the
# "docker" group, in order to let them use Docker without sudo.

set -e

# Install Docker
apt-get update
apt-get -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
apt-get update
apt-get install -y docker-ce=18.06.1~ce~3-0~ubuntu

# Setup workshop user
useradd -m workshop -s /bin/bash
addgroup workshop sudo
addgroup workshop docker
echo "workshop:${vm_password}" | chpasswd
mkdir -p /home/workshop
cp -r /root/.ssh /home/workshop
chown -R workshop:workshop /home/workshop

# Install kubelet, kubectl and kubeadm
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -y kubelet kubeadm kubectl
apt-mark hold kubelet kubeadm kubectl

# Get the machine ready
kubeadm config images pull
sysctl net.bridge.bridge-nf-call-iptables=1
echo "source <(kubectl completion bash)" >> /home/workshop/.bashrc
systemctl daemon-reload
systemctl enable kubelet
systemctl restart kubelet

sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
systemctl restart sshd

if [[ "${init_kube}" == "1" && $(hostname) == *-00 ]]; then
    kubeadm init
    mkdir -p /home/workshop/.kube
    cp -i /etc/kubernetes/admin.conf /home/workshop/.kube/config
    chown workshop:workshop /home/workshop/.kube/config

    kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
    kubectl --kubeconfig=/etc/kubernetes/admin.conf rollout status daemonset weave-net -n kube-system
fi
