#! /bin/bash

# Install Docker on the machine and also add the "workshop" user to the
# "docker" group, in order to let them use Docker without sudo.

set -e

sudo apt-get update
sudo apt-get -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get install -y docker-ce

useradd -m workshop -s /bin/bash
addgroup workshop sudo
addgroup workshop docker
echo "workshop:${vm_password}" | chpasswd